name: Fetch Pronunciation Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # This will run the job daily at midnight

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install axios

    - name: Fetch Pronunciation Data
      run: node fetch-pronunciation.js
      env:
        MERRIAM_WEBSTER_API_KEY: ${{ secrets.MERRIAM_WEBSTER_API_KEY }}

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m 'Fetch and update pronunciation data'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
